### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by tpoisot** [BIO6032/2019_replication_LipstichEtAl_1996#1]
**6 semaines : **
_Note_ : noter notre progression pour chaque semaine (nouvelles idées appliquées, code, modification…).
Faire un retour sur notre progression (appliquer des corrections si nécessaire).

**Semaine 1**
- [x] Trouver et lire les articles les plus pertinents qui ont cité notre article
- [x] Se familiariser avec Julia (fonctions de base, création de figures…)
- [x] Trouver tous les paramètres, variables et équations
- [x] Répliquer une figure simple (exemple : figure 2-b)

**Semaine 2**
- [x] Créer le modèle 

**Semaine 3**
- [x] Refaire les figures 2, 3 et 4

**Semaine 4**
- [ ] Refaire la figure 1

**Semaine 5**
- [x] Avoir refait toutes les figures

- [x] Faire un grand retour sur notre travail et s'assurer que rien n'a été oublié et négligé

**Semaine 6**
- [x] Rédaction

**Comment by sandrinesoeharjono** [comment]
La figure 1 décrit la relation entre les trois variables importantes (la mortalité, la transmission verticale et la transmission horizontale). Nous avons pourtant décidé de l'omettre de cette étude car malgré sa valeur descriptive (et sa beauté), elle n'est pas essentielle aux conclusions de l'étude.
